spring:
  datasource:
    url: jdbc:mysql://localhost:3306/custom_db
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: never

  flyway:
    baseline-on-migrate: true
    enabled: true
    locations: classpath:db/migration